"""add leave balance to employee

Revision ID: f30e2012e29c
Revises: 4f869328433e
Create Date: 2026-07-27 21:37:28.051097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f30e2012e29c'
down_revision = '4f869328433e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('leave_balance', sa.Integer(), nullable=False, server_default='21'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('leave_balance')

    # ### end Alembic commands ###
